AWSTemplateFormatVersion: 2010-09-09

Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./api.yml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref HelloWorldFunction

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../target/cognito-sample.jar
      Handler: MainHandler
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Events:
        ProxyEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY

  HelloWorldFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HelloWorldFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*
